database:
  mysql:
    host: "192.168.200.200"
    port: 3306
    username: "winterchocolates"
    password: "3uRfSQjfpn]"
    dbname: "hrms"
    charset: "utf8mb4"
    parse_time: true
    max_retries: 3
    retry_interval: 5
    max_open_conn: 100
    max_lifetime: 3600
  redis:
    host: "192.168.200.200"
    port: 6379
    password: "3uRfSQjfpn]"
    db: 0
    pool_size: 20
    min_idle_conns: 5
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout:  3s
    max_retries: 3
    retry_interval: 5

server:
  port: "8081"
  mode: "debug"

jwt:
  secret: "winterchocolates"